# -------------------------------------------------------------
# Site Information
# -------------------------------------------------------------
title: "Kieran Douglas"
description: "Economics graduate student at UC Davis"
url: "https://kierandouglas.com"    # Full URL to your site
baseurl: ""                         # Leave empty for root domain

# -------------------------------------------------------------
# Author Information
# -------------------------------------------------------------
author:
  name: "Kieran Douglas"
  email: "kcdouglas@ucdavis.edu"

# -------------------------------------------------------------
# Theme & Build Settings
# -------------------------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-sitemap   # (optional, supported by GitHub Pages)

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# -------------------------------------------------------------
# Collections
# -------------------------------------------------------------
collections:
  projects:
    output: true
    permalink: /my-work/:name/

# -------------------------------------------------------------
# Defaults
# -------------------------------------------------------------
defaults:
  - scope:
      path: ""         # all files
    values:
      layout: "default"
  - scope:
      path: ""         # all project items
      type: "projects"
    values:
      layout: "project"   # a layout you'll add below

# -------------------------------------------------------------
# Permalinks & File Handling
# -------------------------------------------------------------
permalink: /:categories/:title/
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .gitignore
  - _site
